---
swagger: '2.0'
info:
  version: 0.1.0
  title: "Where's Charlie?"
paths:
  /locations:
    get:
      tags:
        - locations
      summary: List location updates.
      operationId: wheres_charlie.controllers.location_controllers.locations_get
      parameters:
        - name: per_page
          in: query
          description: The maximum number of entries returned. Default `10` max `200`.
          type: integer
          minimum: 1
          maximum: 200
          default: 10
        - name: page
          in: query
          description: The page to return. Default `1`.
          type: integer
          default: 1
        - name: reverse_chronological
          in: query
          description: Return the results in reverse chronological order (newest first) if `true`. In chronological order if `false`. Default `true`.
          type: boolean
          default: true
        - name: show_hidden
          in: query
          description: Whether to show hidden location updates. Only available to administrators.
          type: boolean
          default: false
      responses:
        '200':
          description: The locations were retreived.
          schema:
            $ref: '#/definitions/ArrayOfLocations'
    post:
      tags:
        - locations
      operationId: wheres_charlie.controllers.location_controllers.locations_post
      summary: Post a location update.
      parameters:
        - name: body
          in: body
          description: The `Location` object to be created.
          required: true
          schema:
            $ref: '#/definitions/Location'
      security:
        - wheres_charlie_key: []
      responses:
        '201':
          description: The location update was created.
          schema:
            $ref: '#/definitions/Location'
  '/locations/{id}':
    get:
      tags:
        - locations
      summary: Get a location update.
      operationId: wheres_charlie.controllers.location_controllers.locations_id_get
      parameters:
        - name: id
          in: path
          description: The `id` of the location update to retreive.
          required: true
          type: string
          format: byte
      responses:
        '200':
          description: The location update was retreived.
          schema:
            $ref: '#/definitions/Location'
    delete:
      tags:
        - locations
      summary: Delete a location update.
      operationId: wheres_charlie.controllers.location_controllers.locations_id_delete
      parameters:
        - name: id
          in: path
          description: The `id` of the location update to delete.
          required: true
          type: string
          format: byte
      security:
        - wheres_charlie_key: []
      responses:
        '204':
          description: The location update was deleted.
    patch:
      tags:
        - locations
      summary: 'Update a location update. `location`, `dateTime`, and `hidden` can be updated by that user or admin. `userId` can be updated by admin.'
      operationId: wheres_charlie.controllers.location_controllers.locations_id_patch
      parameters:
        - name: id
          in: path
          description: The `id` of the location update to be patched.
          required: true
          type: string
          format: byte
        - name: body
          in: body
          description: The partially-filled `Location` object used to patch.
          required: true
          schema:
            $ref: '#/definitions/Location'
      security:
        - wheres_charlie_key: []
      responses:
        '200':
          description: The location update was patched.
          schema:
            $ref: '#/definitions/Location'
  /token:
    post:
      tags:
        - users
      summary: Stuff
      operationId: wheres_charlie.controllers.token_controllers.token_post
      parameters:
        - name: body
          in: body
          description: Stuff
          required: true
          schema:
            type: object
            required:
              - username
              - password
              - scopes
            properties:
              username:
                type: string
              password:
                type: string
              scopes:
                type: array
                items:
                  type: string
                  enum:
                    - admin
                    - 'user:post'
                    - 'user:profile'
      responses:
        '200':
          description: The authentication succeded.
          schema:
            $ref: '#/definitions/AccessToken'

  /users:
    get:
      tags:
        - users
      summary: List users.
      operationId: wheres_charlie.controllers.user_controllers.users_get
      parameters:
        - name: per_page
          in: query
          description: The maximum number of entries returned. Default `10` max `200`.
          type: integer
          minimum: 1
          maximum: 200
          default: 10
        - name: page
          in: query
          description: The page to return. Default `0`.
          type: integer
          default: 10
        - name: show_hidden
          in: query
          description: Whether to show hidden users. Only available to administrators. Default `false`; `true` is ignored if issued by a non-administrator.
          type: boolean
          default: false
      responses:
        '200':
          description: The users were retreived.
          schema:
            $ref: '#/definitions/ArrayOfUsers'
    post:
      tags:
        - users
      summary: Create a user.
      operationId: wheres_charlie.controllers.user_controllers.users_post
      parameters:
        - name: body
          in: body
          description: The `User` object to be created.
          required: true
          schema:
            $ref: '#/definitions/User'
      security:
        - wheres_charlie_key: []
      responses:
        '201':
          description: The user was created.
          schema:
            $ref: '#/definitions/User'
  '/users/{id}':
    get:
      tags:
        - users
      summary: Get a user.
      operationId: wheres_charlie.controllers.user_controllers.users_id_get
      parameters:
        - name: id
          in: path
          description: The `id` of the user to retreive.
          required: true
          type: string
          format: byte
      responses:
        '200':
          description: The user was retreived.
          schema:
            $ref: '#/definitions/User'
    delete:
      tags:
        - users
      summary: Delete a user.
      operationId: wheres_charlie.controllers.user_controllers.users_id_delete
      parameters:
        - name: id
          in: path
          description: The `id` of the user to delete.
          required: true
          type: string
          format: byte
      security:
        - wheres_charlie_key: []
      responses:
        '204':
          description: The user was deleted.
    patch:
      tags:
        - users
      summary: Update a user. `name` and `hidden` can be updated by that user or an admin; `admin` can be updated by an admin.
      operationId: wheres_charlie.controllers.user_controllers.users_id_patch
      parameters:
        - name: id
          in: path
          description: The `id` of the user to update.
          required: true
          type: string
          format: byte
        - name: body
          in: body
          description: The partially-filled `User` object used to patch.
          required: true
          schema:
            $ref: '#/definitions/User'
      security:
        - wheres_charlie_key: []
      responses:
        '200':
          description: The user was patched.
          schema:
            $ref: '#/definitions/User'
  '/users/{id}/locations':
    get:
      tags:
        - users
      summary: "List a user's location updates."
      operationId: wheres_charlie.controllers.user_controllers.users_id_locations_get
      parameters:
        - name: id
          in: path
          description: The `id` of the user whose location updates are to be retreived.
          required: true
          type: string
          format: byte
        - name: per_page
          in: query
          description: The maximum number of entries returned. Default `10` max `200`.
          type: integer
          minimum: 1
          maximum: 200
          default: 10
        - name: page
          in: query
          description: The page to return. Default `1`.
          type: integer
          default: 1
        - name: reverse_chronological
          in: query
          description: Return the results in reverse chronological order (newest first) if `true`. In chronological order if `false`. Default `true`.
          type: boolean
          default: true
        - name: show_hidden
          in: query
          description: Whether to show hidden location updates. Only available to administrators.
          type: boolean
          default: false
      responses:
        '200':
          description: The locations were retreived.
          schema:
            $ref: '#/definitions/ArrayOfLocations'
  '/users/{id}/locations/latest':
    get:
      tags:
        - users
      summary: "Retreive a user's most recent location update."
      operationId: wheres_charlie.controllers.user_controllers.users_id_locations_latest_get
      parameters:
        - name: id
          in: path
          description: The `id` of the user whose latest location update is to be retreived.
          required: true
          type: string
          format: byte
      responses:
        '200':
          description: The latest location update was retreived.
          schema:
            $ref: '#/definitions/Location'
securityDefinitions:
  wheres_charlie_key:
    type: apiKey
    description: JWT-based api key authorization.
    name: Authorization
    in: header
definitions:
  Location:
    type: object
    required:
      - location_string
    properties:
      location_id:
        type: string
        format: byte
      user_id:
        type: string
        format: byte
      location_string:
        type: string
      date_time:
        type: string
        format: date-time
      active:
        type: boolean
  User:
    type: object
    required:
      - name
    properties:
      user_id:
        type: string
        format: byte
      name:
        type: string
      active:
        type: boolean
      roles:
        type: array
        items:
          type: string
          enum:
            - admin
            - 'user:post'
            - 'user:profile'
  AccessToken:
    type: object
    required:
      - access_token
    properties:
      access_token:
        type: string
  ArrayOfLocations:
    type: array
    items:
      $ref: '#/definitions/Location'
  ArrayOfUsers:
    type: array
    items:
      $ref: '#/definitions/User'
